### ISSUE TITLE
Extend to arbitrary word length

### ISSUE THREAD

**Issue by MohrMa2** [chummersone/chummersone.github.io#1]
I stumbled across the Q-format converter, which came very handy.

What is missing, is special formats, like signed Q19.4 or similar, where the word size is not a multiple of byte. 

Is the source code available?

**Comment by chummersone** [comment]
The conversion is performed by the rather inelegant JavaScript, which you can review by looking at the page source. Also, Q19.4 corresponds to a 24-bit number, which is already supported.

**Comment by MohrMa2** [comment]
Yeah you are right in this case. But sometimes, I have really arbitrary formats, signed Q8.2 or unsigned Q14.0 similar.
But I will check the code and try to solve it.

**Comment by chummersone** [comment]
In hindsight, rather than tinkering with JS, what you need can probably be achieved by simply changing the HTML form control that chooses the number of bits. See `<select id="num_bits">` on line 787.

**Comment by MohrMa2** [comment]
I glimpsed over the code and had the same idea. Was not sure, if in JS maybe the usual bit length are implicitly assumed.
But I will try and hope, the code is generic enough. 

Thanks for your help. And, man you are fast in replying.

**Comment by chummersone** [comment]
I had a quick look over the code and I don't see any specific assumptions related to bytes; everything seems to be based on the number of bits. The only exception appears to be when displaying results in hex; I couldn't say for certain whether the sign bit will be extended through the most-significant nybble, but I doubt it. Note also that JS integers are 32-bit, which is the ceiling on the bit count.
