### ISSUE TITLE
support for 64bit fixed values

### ISSUE THREAD

**Issue by hinxx** [chummersone/chummersone.github.io#5]
I've forked your repo and tried to make it handle 64bit word sizes by editing couple of lines of code as seen here https://github.com/hinxx/fixedint.

Do you think this is correct way of doing it?

**Comment by chummersone** [comment]
Hey. Looks fine to me. Some time ago I changed the internals to use `BigInt`, so it should be relatively agnostic to word size. I noticed the changes to the `_wordMask` method, but I think the current implementation is a hangover from the pre-`BigInt` implementation. You need only keep the `if` branch.

**Comment by chummersone** [comment]
FWIW, I made the change to `_wordMask`, and added 64-bit as an option.

**Comment by hinxx** [comment]
Thanks for update !!
