### ISSUE TITLE
Value of 1 with Q1.63

### ISSUE THREAD

**Issue by hinxx** [chummersone/chummersone.github.io#6]
If I understand correctly with Q1.63 signed conversion values are in range 0.99999999 .. -1 and trying to convert 1 should raise an `Out of Range` error (like it happens when doing Q1.31 signed conversion).

![Screenshot_2024-09-20_10-01-28](https://github.com/user-attachments/assets/0f4217cb-babe-41eb-8bc4-bd6d8b7e6370)

![Screenshot_2024-09-20_10-01-50](https://github.com/user-attachments/assets/f058396a-8df9-4769-a420-55bfc1def84c)

**Comment by chummersone** [comment]
The precision of 2^-63 is much smaller than the machine epsilon of JavaScript (which is double precision floating point, in which case the machine epsilon is something like 2^-53). So this is a very reasonable rounding error. Not much we can do about that in JavaScript.
